apiVersion: apps/v1
kind: Deployment
metadata:
  name: gomall-redis
spec:
  selector:
    matchLabels:
      app: gomall-redis
  template:
    metadata:
      labels:
        app: gomall-redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
