apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: huajuan6848/product:lab2-unhealthy
          ports:
            - containerPort: 8881
          livenessProbe:
            tcpSocket:
              port: 8881
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 8881
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: config
              mountPath: /app/conf/dev
      volumes:
        - name: config
          configMap:
            name: product-config
